"""Added title in chat

Revision ID: 61c688a81e5b
Revises: 57f483d0974f
Create Date: 2025-04-17 10:34:38.897593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c688a81e5b'
down_revision: Union[str, None] = '57f483d0974f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('title', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'chats', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='unique')
    op.drop_column('chats', 'title')
    # ### end Alembic commands ###
